### ISSUE TITLE
Stay logged in at multiple devices

### ISSUE THREAD

**Issue by oed** [cthit/hubbIT-old#130] opened 2016-03-28 11:31 UTC
If I log in from my phone I'm logged out from my laptop, and vice versa. It should be possible to be logged in from multiple devices at the same time.

tl;dr: Add support for multiple sessions.

**Comment by lindskogen** [comment] 2016-03-28 11:34
Not an issue with hubbIT. 
Will be solved with account.
Duplicate of https://github.com/cthit/auth/issues/1

**Closed as completed by lindskogen** 2016-03-28 11:34 UTC
